name: ieee_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  lottie: ^2.6.0
  firebase_core: ^2.15.1
  get_it: ^7.6.4
  flutter_svg: ^2.0.7
  firebase_auth: ^4.9.0
  get: ^4.6.6
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/logo.json
    - assets/json/empty.json
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/success.json
    - assets/image/firstframe.png
    - assets/image/lock.jpg
    - assets/image/profileimage.png
    - assets/image/secondframe.png
    - assets/image/art.png
    - assets/image/chef.png
    - assets/image/logo.png
    - assets/image/student.png
    - assets/image/EllipseBlue.png
    - assets/image/EllipseWhite.png
    - assets/svg/hollow_circle_ic.svg
    - assets/svg/solid_circle_ic.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
